# Web Server fils by Louis292 V1.0.0:

# API key
secret_key: "votre_cle_secrete"

# Utilisateurs:
users:
  admin: "password"
  user1: "user1password"

# API multiple key:
api_keys:
  user1: "api_key_12345"
  user2: "api_key_67890"

# Logs:
logging:
  enabled: true
  log_file: "logs/app.log"

# Port du serveur:
port: 5000

# Développer mode:
debug: false
